- name: Install client display script
  hosts: clients
  tasks:

    - name: Copy script
      ansible.builtin.copy:
        src: ../client.py
        dest: ~/demo.py
        mode: preserve

- name: Install broker display script
  hosts: brokers
  tasks:
    - name: Copy script
      ansible.builtin.copy:
        src: ../broker.py
        dest: ~/demo.py
        mode: preserve

- name: Install Python dependencies, set to auto-run
  hosts: all

  tasks:
    - name: Add Debian testing apt repo
      ansible.builtin.apt_repository:
        repo: deb     http://ftp.de.debian.org/debian/    testing main contrib non-free
      become: true

    - name: Set apt priorities
      ansible.builtin.copy:
        content: |
          Package: *
          Pin: release a=stable
          Pin-Priority: 900

          Package: *
          Pin: release o=Debian
          Pin-Priority: -10
        dest: /etc/apt/preferences.d/confluent-kafka-python.pref
      become: true

    - name: Install apt dependencies from Debian testing
      ansible.builtin.apt:
        default_release: testing
        name:
          - librdkafka-dev
      become: true

    - name: Install apt dependencies
      ansible.builtin.apt:
        name:
          - ipython3
          - python3-confluent-kafka
          - python3-gpiozero
          - python3-rich
          - python3-typer
          - python3-virtualenv
      become: true

    - name: Copy requirements file
      ansible.builtin.copy:
        src: ../requirements.txt
        dest: requirements.txt

    - name: Install Python packages
      ansible.builtin.pip:
        virtualenv: ~/env
        virtualenv_site_packages: true
        requirements: ~/requirements.txt

    - name: Get Kafka server IDs
      ansible.builtin.set_fact:
        bootstrap_servers: "{% for host in groups['brokers'] %}{{ host }}{% if not loop.last %},{% endif %}{% endfor %}"

    - name: Create /usr/local/lib/systemd/system
      ansible.builtin.file:
        dest: /usr/local/lib/systemd/system
        state: directory
      become: true

    - name: Auto-run demo program on /dev/tty1
      ansible.builtin.copy:
        content: |
          [Unit]
          Description=Start GCN Demo on tty1
          After=getty.target
          Conflicts=getty@tty1.service

          [Service]
          Type=exec
          ExecStart=/home/gcndemo/env/bin/python /home/gcndemo/demo.py {{bootstrap_servers}} {% if kafka_topic is defined %}{{kafka_topic}}{% endif %}

          StandardInput=tty-force
          StandardOutput=inherit
          StandardError=journal
          TTYPath=/dev/tty1

          [Install]
          WantedBy=multi-user.target
        dest: /usr/local/lib/systemd/system/gcndemo.service
      become: true
      register: needs_daemon_reload

    - name: Restart demo program
      ansible.builtin.systemd_service:
        name: gcndemo.service
        daemon_reload: "{{needs_daemon_reload.changed}}"
        enabled: true
        state: restarted
      become: true
