- name: Install client display script
  hosts: clients
  tasks:

    - name: Copy script
      ansible.builtin.copy:
        src: ../client.py
        dest: ~/demo.py
        mode: preserve

- name: Install broker display script
  hosts: brokers
  tasks:
    - name: Copy script
      ansible.builtin.copy:
        src: ../admin.py
        dest: ~/demo.py
        mode: preserve

- name: Install Python dependencies, set to auto-run
  hosts: all

  tasks:
    - name: Get Kafka server IDs
      ansible.builtin.set_fact:
        bootstrap_servers: "{% for host in groups['brokers'] %}{{ host }}:9092{% if not loop.last %},{% endif %}{% endfor %}"

    - name: Install apt dependencies
      ansible.builtin.apt:
        name:
          - ipython3
          - python3-confluent-kafka
          - python3-gpiozero
          - python3-rich
          - python3-typer
          - python3-virtualenv
      become: true

    - name: Copy requirements file
      ansible.builtin.copy:
        src: ../requirements.txt
        dest: requirements.txt

    - name: Install Python packages
      ansible.builtin.pip:
        virtualenv: ~/env
        virtualenv_site_packages: true
        requirements: ~/requirements.txt

    - name: Auto-run demo program on /dev/tty1
      ansible.builtin.lineinfile:
        line: 'if [ $(tty) = /dev/tty1 ]; then ~/env/bin/python ~/demo.py {{bootstrap_servers}} {% if kafka_topic is defined %}{{kafka_topic}}{% endif %}; fi  # launch GCN demo'
        search_string: '# launch GCN demo'
        insertafter: EOF
        dest: /home/gcndemo/.profile

    - name: Restart demo program
      ansible.builtin.shell: pkill -HUP -t tty1
