- name: Configure all machines to derive time from gcndemo1
  hosts: all
  become: true

  tasks:
    - name: Install Chrony on all hosts
      ansible.builtin.apt:
        name: chrony

- name: Configure one machine as an isolated NTP server
  hosts: ntpd
  become: true
  tasks:
    - ansible.builtin.copy:
        content: |
          allow 10.0.42.0/16
          local stratum 8
          makestep 1 -1
        dest: /etc/chrony/conf.d/local.conf
      register: updated_conf

    - ansible.builtin.systemd_service:
        name: chrony.service
        state: restarted
      when: updated_conf.changed or updated_sources.changed

- name: Configure all other machines to get their time from the isolated NTP server
  hosts: all:!ntpd
  become: true
  tasks:

    - ansible.builtin.copy:
        content: |
          server {{groups.ntpd[0]}} iburst
          makestep 1 -1
        dest: /etc/chrony/sources.d/local.sources
      register: restart_needed

    - ansible.builtin.systemd_service:
        name: chrony.service
        state: restarted
      when: restart_needed.changed
