- name: Stop all brokers, nuke their data
  hosts: brokers
  become: true

  tasks:
    - name: Stop confluent-kafka.service
      ansible.builtin.systemd_service:
        name: confluent-kafka.service
        enabled: true
        state: stopped

    - name: Stop confluent-zookeeper.service
      ansible.builtin.systemd_service:
        name: confluent-zookeeper.service
        state: stopped

    - name: Nuke contents of Zookeeper and Kafka data dirs
      ansible.builtin.shell: rm -rf /var/lib/zookeeper/* /var/lib/kafka/*
