- name: Install systemd-gpio
  hosts: all
  become: true
  tasks:
    - name: Download Debian package
      ansible.builtin.apt:
        deb: https://asd.gsfc.nasa.gov/Leo.Singer/python3-systemd-gpio_0.1.0-1_all.deb

- name: Configure poweroff safe message service
  hosts: all
  become: true
  tasks:
    - name: Create service
      ansible.builtin.copy:
        content: |
          [Unit]
          Description=Display a message to the Mini PiTFT screen that it is safe to turn off the computer
          Conflicts=getty@tty1.service
          DefaultDependencies=no
          Before=halt.target shutdown.target reboot.target

          [Service]
          Type=oneshot
          ExecStart=/bin/echo '\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nIt is now safe\nto turn off\nyour computer.'
          RemainAfterExit=yes
          StandardInput=tty-force
          StandardOutput=inherit
          StandardError=journal
          TTYPath=/dev/tty1

          [Install]
          WantedBy=halt.target shutdown.target reboot.target
        dest: /usr/local/lib/systemd/system/safe-to-poweroff.service
      register: needs_daemon_reload

    - name: Enable service
      ansible.builtin.systemd_service:
        name: safe-to-poweroff.service
        daemon_reload: "{{ needs_daemon_reload.changed }}"
        enabled: true

- name: Configure buttons for brokers
  hosts: brokers
  become: true
  tasks:
    - name: Configure GPIO23
      ansible.builtin.copy:
        content: |
          GPIO_HOLD_TIME="5"
          GPIO_WHEN_HELD="poweroff"
        dest: /etc/gpio/23

    - name: Restart GPIO23 service
      ansible.builtin.systemd_service:
        name: gpio@23.service
        enabled: true
        state: restarted

    - name: Configure GPIO24
      ansible.builtin.copy:
        content: |
          GPIO_WHEN_PRESSED="systemctl restart gcndemo.service"
        dest: /etc/gpio/24

    - name: Restart GPIO24 service
      ansible.builtin.systemd_service:
        name: gpio@24.service
        enabled: true
        state: restarted

- name: Configure buttons for clients
  hosts: clients
  become: true
  tasks:
    - name: Configure GPIO24
      ansible.builtin.copy:
        content: |
          GPIO_HOLD_TIME="5"
          GPIO_WHEN_HELD="poweroff"
        dest: /etc/gpio/24

    - name: Restart GPIO24 service
      ansible.builtin.systemd_service:
        name: gpio@24.service
        enabled: true
        state: restarted

    - name: Configure GPIO23
      ansible.builtin.copy:
        content: |
          GPIO_WHEN_PRESSED="systemctl restart gcndemo.service"
        dest: /etc/gpio/23

    - name: Restart GPIO24 service
      ansible.builtin.systemd_service:
        name: gpio@23.service
        enabled: true
        state: restarted
