- name: Install systemd-gpio
  hosts: all
  become: true
  tasks:
    - name: Download Debian package
      ansible.builtin.apt:
        deb: https://nasa-gcn.github.io/systemd-gpio/python3-systemd-gpio_0.0.1~pre1_all.deb

- name: Configure buttons for brokers
  hosts: brokers
  become: true
  tasks:
    - name: Configure GPIO23
      ansible.builtin.copy:
        content: |
          GPIO_HOLD_TIME="5"
          GPIO_WHEN_HELD="poweroff"
          GPIO_WHEN_PRESSED="systemctl restart gcndemo.service"
        dest: /etc/gpio/23

    - name: Restart GPIO23 service
      ansible.builtin.systemd_service:
        name: gpio@23.service
        enabled: true
        state: restarted

    - name: Configure GPIO24
      ansible.builtin.copy:
        content: |
          GPIO_WHEN_PRESSED="systemctl restart confluent-kafka.service"
        dest: /etc/gpio/24

    - name: Restart GPIO24 service
      ansible.builtin.systemd_service:
        name: gpio@24.service
        enabled: true
        state: restarted

- name: Configure buttons for clients
  hosts: clients
  become: true
  tasks:
    - name: Configure GPIO24
      ansible.builtin.copy:
        content: |
          GPIO_HOLD_TIME="5"
          GPIO_WHEN_HELD="poweroff"
          GPIO_WHEN_RELEASED="systemctl restart gcndemo.service"
        dest: /etc/gpio/24

    - name: Restart GPIO24 service
      ansible.builtin.systemd_service:
        name: gpio@24.service
        enabled: true
        state: restarted
