- name: Set up proxy through lab gateway system
  hosts: all
  become: true

  tasks:
    - name: Set up HTTP_PROXY/HTTPS_PROXY environment variables
      ansible.builtin.lineinfile:
        line: "{{item}}=http://10.0.0.1:3128/"
        dest: /etc/environment
      loop:
        - http_proxy
        - https_proxy
        - HTTP_PROXY
        - HTTPS_PROXY

    - name: Set up NO_PROXY environment variables
      ansible.builtin.lineinfile:
        line: "{{item}}=127.0.0.1,localhost"
        dest: /etc/environment
      loop:
        - no_proxy
        - NO_PROXY

    - name: Set up DNS
      ansible.builtin.copy:
        content: |
          nameserver 10.0.0.1
        dest: /etc/resolv.conf
