- name: Set up proxy through lab gateway system
  hosts: all
  become: true

  tasks:
    - name: Disable WiFi and Bluetooth
      ansible.builtin.lineinfile:
        insertafter: \[all\]
        line: "{{item}}"
        dest: /boot/config.txt
      loop:
        - dtoverlay=disable-bt
        - dtoverlay=disable-wifi

    - name: Set up HTTP_PROXY/HTTPS_PROXY environment variables
      ansible.builtin.lineinfile:
        line: "{{item}}=http://10.0.0.1:3128/"
        dest: /etc/environment
      loop:
        - http_proxy
        - https_proxy
        - HTTP_PROXY
        - HTTPS_PROXY

    - name: Set up NO_PROXY environment variables
      ansible.builtin.lineinfile:
        line: "{{item}}=127.0.0.1,localhost"
        dest: /etc/environment
      loop:
        - no_proxy
        - NO_PROXY

    - name: Install Chrony on all hosts
      ansible.builtin.apt:
        name: chrony

- name: Configure one machine as an isolated NTP server
  hosts: ntpd
  become: true
  tasks:
    - ansible.builtin.copy:
        content: |
          allow 10.0.42.0/16
        dest: /etc/chrony/conf.d/local.conf
      register: restart_needed

    - ansible.builtin.copy:
        content: |
          local
          server 10.0.0.1
        dest: /etc/chrony/sources.d/gateway.sources
      register: restart_needed

    - ansible.builtin.systemd_service:
        name: chrony.service
        state: restarted
      when: restart_needed.changed

- name: Configure all other machines to get their time from the isolated NTP server
  hosts: all:!ntpd
  become: true
  tasks:

    - ansible.builtin.copy:
        content: |
          server {{groups.ntpd[0]}} iburst
        dest: /etc/chrony/sources.d/local.sources
      register: restart_needed

    - ansible.builtin.systemd_service:
        name: chrony.service
        state: restarted
      when: restart_needed.changed
