- name: Install software on brokers
  hosts: brokers
  become: true

  tasks:
    - name: Get Kafka server ID
      ansible.builtin.set_fact:
        kafka_server_id: "{{ ansible_play_hosts_all.index(inventory_hostname) + 1 }}"
        bootstrap_servers: "{% for host in ansible_play_hosts_all %}{{ host }}:9092{% if not loop.last %},{% endif %}{% endfor %}"

    - name: Add Confluent Debian Key
      ansible.builtin.apt_key:
        url: https://packages.confluent.io/deb/7.8/archive.key

    - name: Add Confluent Debian Repo
      ansible.builtin.apt_repository:
        repo: deb [arch=amd64] https://packages.confluent.io/deb/7.8 stable main

    - name: Install Confluent Platform
      ansible.builtin.apt:
        name:
          - confluent-kafka
          - default-jdk-headless

    - name: Create systemd directories
      ansible.builtin.file:
        dest: /usr/local/lib/systemd/system/confluent-{{ item }}.service.d
        state: directory
      loop:
        - zookeeper
        - kafka

    - name: Restart Zookeeper and Kafka if they ever halt or crash unexpectedly
      ansible.builtin.copy:
        content: |
          [Service]
          Restart=always
        dest: /usr/local/lib/systemd/system/confluent-{{ item }}.service.d/autorestart.conf
      loop:
        - zookeeper
        - kafka

    - name: Work around https://github.com/confluentinc/schema-registry/pull/917
      ansible.builtin.copy:
        content: |
          [Unit]
          Description=Apache Kafka - Zookeeper - target
          Requires=confluent-zookeeper.service
          [Install]
          WantedBy=multi-user.target
        dest: /usr/local/lib/systemd/system/confluent-zookeeper.target

    - name: Configure Zookeeper
      ansible.builtin.copy:
        content: |
          dataDir=/var/lib/zookeeper
          clientPort=2181
          maxClientCnxns=0
          admin.enableServer=false
          initLimit=5
          syncLimit=2
          {% for host in ansible_play_hosts_all %}
          server.{{ loop.index }}={{ host }}:2888:3888
          {% endfor %}
        dest: /etc/kafka/zookeeper.properties

    - name: Configure Kafka
      ansible.builtin.copy:
        content: |
          broker.id={{ kafka_server_id }}
          listeners=PLAINTEXT://{{ inventory_hostname }}:9092
          log.dirs=/var/lib/kafka
          default.replication.factor={{ ansible_play_hosts_all|length }}
          min.insync.replicas=2
          replica.lag.time.max.ms = 1000
          replica.socket.timeout.ms = 1000
          request.timeout.ms = 1000
          zookeeper.session.timeout.ms = 1000
          socket.connection.setup.timeout.ms = 500

          zookeeper.connect={% for host in ansible_play_hosts_all %}{{ host }}:2181{% if not loop.last %},{% endif %}{% endfor %}

          group.initial.rebalance.delay.ms=0
        dest: /etc/kafka/server.properties

    - name: Set Zookeeper ID
      ansible.builtin.copy:
        content: "{{ kafka_server_id }}"
        dest: /var/lib/zookeeper/myid

    - name: Start confluent-zookeeper.service
      ansible.builtin.systemd_service:
        name: confluent-zookeeper.service
        enabled: true
        state: started

    - name: Start confluent-zookeeper.target
      ansible.builtin.systemd_service:
        name: confluent-zookeeper.target
        enabled: true
        state: started

    - name: Start confluent-kafka.service
      ansible.builtin.systemd_service:
        name: confluent-kafka.service
        enabled: true
        state: started

    - name: Create Kafka topics
      ansible.builtin.shell: kafka-topics --bootstrap-server {{bootstrap_servers}} --create --if-not-exists --topic {{item}}
      loop:
        - red
        - green
        - blue
